### ISSUE TITLE
Py 2.7 build not supported on Windows

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/minorminer#40]
I am unable to build on Windows for Python 2.7: build reports "fatal error C1083: Cannot open include file: 'chrono': No such file or directory". 
Apparently, <chrono> requires at least MS VS 14 compiler; however, MS VS versions above 9 no longer support Python 2.7.
One solution is to replace <chrono> with boost time&date.
I built in Python 3 using MS VS 14 standalone build tool's compiler. (I can build for Python 2.7 on a unix platform.)
Maybe for building this tool, Windows support should be limited to Python 3 (and stated in the README)?

**Comment by bellert** [comment]
AppVeyor is able to build on Windows for Python 2.7, e.g., https://ci.appveyor.com/project/dwave-adtt/minorminer/build/1.0.123
Maybe compare what you're doing with what's being done here: https://github.com/dwavesystems/minorminer/blob/master/appveyor.yml

**Comment by JoelPasvolsky** [comment]
I was looking here: https://wiki.python.org/moin/WindowsCompilers
![image](https://user-images.githubusercontent.com/34041130/41424622-6c6e192c-6fb3-11e8-890b-333f662f3f5e.png)

But there are so many versions of 14 it could be the one I'm using.

**Comment by bellert** [comment]
Hmm, closing for now, since it is possible to build this (as AppVeyor does), and we're not expecting many users to build from source.
